<?php

return [
    'guild' => 'manifesto',
    'locale' => 'pt_BR',
    'realm' => 'azralon',
    'namespaceStatic' => 'static-us',
    'namespaceProfile' => 'profile-us',
    'urlAuthToken' => 'https://us.battle.net/oauth/token',
    'urlAuthRedirect' => 'https://us.battle.net/oauth/authorize',
    'urlBaseData' => 'https://us.api.blizzard.com/data/wow',
    'urlBaseProfile' => 'https://us.api.blizzard.com/profile/wow/character',
    'urlCharacterWow' => 'https://worldofwarcraft.com/pt-br/character/us',
    'urlCharacterRaiderio' => 'https://raider.io/characters/us/azralon/',
    'classes' => [
        1 => 'Guerreiro',
        2 => 'Paladino',
        3 => 'Caçador',
        4 => 'Ladino',
        5 => 'Sacerdote',
        6 => 'Cavaleiro da Morte',
        7 => 'Xamã',
        8 => 'Mago',
        9 => 'Bruxo',
        10 => 'Monge',
        11 => 'Druida',
        12 => 'Caçador de Demônios',
    ],
    'races' => [
        1 => 'Humano',
        2 => 'Orc',
        3 => 'Anão',
        4 => 'Elfo Noturno',
        5 => 'Morto-vivo',
        6 => 'Tauren',
        7 => 'Gnomo',
        8 => 'Troll',
        9 => 'Goblin',
        10 => 'Elfo Sangrento',
        11 => 'Draenei',
        22 => 'Worgen',
        24 => 'Pandaren',
        25 => 'Pandaren',
        26 => 'Pandaren',
        27 => 'Filho da Noite',
        28 => 'Tauren Altamontês',
        29 => 'Elfo Caótico',
        30 => 'Draenei Forjado a Luz',
        31 => 'Troll Zandalari',
        32 => 'Kultireno',
        34 => 'Anão Ferro Negro',
        35 => 'Vulpera',
        36 => 'Orc Mag\'har',
        37 => 'Gnomecânico',
  ],
];
